### ISSUE TITLE
[AWS Cloud] Add option to change service code in collector plugin

### ISSUE THREAD

**Issue by whdalsrnt** [spaceone-dev/plugin-aws-cloud-service-inven-collector#417]
- AWS EC2 : https://github.com/spaceone-dev/plugin-aws-ec2-inven-collector
- AWS CS : https://github.com/spaceone-dev/plugin-aws-cloud-service-inven-collector
- Azure VM : https://github.com/spaceone-dev/plugin-azure-vm-inven-collector
- Azure CS : https://github.com/spaceone-dev/plugin-azure-cloud-service-inven-collector
- Google Cloud : https://github.com/spaceone-dev/plugin-google-cloud-inven-collector

```
options: 
  service_code_mapper: 
    AmazonEC2: Amazon Elastic Computing
    ...
```
