### ISSUE TITLE
Collecting Error: An error occurred (TooManyRequestsException) when calling the GetResources operation (reached max retries: 4): Too Many Requests

### ISSUE THREAD

**Issue by jihyungSong** [spaceone-dev/plugin-aws-cloud-service-inven-collector#441]
```yaml
  - additional:
      cloud_service_group: APIGateway
      cloud_service_type: API
      domain_id: domain-xxxxx
      provider: aws
      resource_id: u9lxxxxx
      resource_type: inventory.CloudService
    error_code: ERROR_PLUGIN
    message: 'An error occurred (TooManyRequestsException) when calling the GetResources
      operation (reached max retries: 4): Too Many Requests'
```
